### ISSUE TITLE
Does not work with Python 3.14

### ISSUE THREAD

**Issue by jajanzen** [mundungus443/py-rolldice#14]
Sample code no longer works (perhaps because of regex update)

  import rolldice
  result, explanation = rolldice.roll_dice('12d6 + 10')

Error:
Traceback (most recent call last):
  File "C:\Users\johnj\Documents\DVL\pydice\venv\Lib\site-packages\rolldice\rolldice.py", line 855, in roll_dice
    final_result = parser.eval(''.join([str(x) for x in results])) #Call the parser to parse into one value
  File "C:\Users\johnj\Documents\DVL\pydice\venv\Lib\site-packages\rolldice\rolldice.py", line 151, in eval
    return self._eval(ast.parse(expr.strip()).body[0].value)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johnj\Documents\DVL\pydice\venv\Lib\site-packages\rolldice\rolldice.py", line 165, in _eval
    return handler(node)
  File "C:\Users\johnj\Documents\DVL\pydice\venv\Lib\site-packages\rolldice\rolldice.py", line 196, in _eval_binop
    return self.operators[type(node.op)](self._eval(node.left),
                                         ~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\johnj\Documents\DVL\pydice\venv\Lib\site-packages\rolldice\rolldice.py", line 165, in _eval
    return handler(node)
  File "C:\Users\johnj\Documents\DVL\pydice\venv\Lib\site-packages\rolldice\rolldice.py", line 175, in _eval_num
    return node.n
           ^^^^^^
AttributeError: 'Constant' object has no attribute 'n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\johnj\Documents\DVL\pydice\test.py", line 2, in <module>
    result, explanation = rolldice.roll_dice('12d6 + 10')
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\johnj\Documents\DVL\pydice\venv\Lib\site-packages\rolldice\rolldice.py", line 859, in roll_dice
    raise DiceOperatorException('Error parsing operators and or functions')
rolldice.rolldice.DiceOperatorException: Error parsing operators and or functions

**Comment by jajanzen** [comment]
Problem is with Python 3.14. Works with Python 3.12.9.  May work with later versions as well
py-rolldice==0.4.0
regex==2025.11.3

**Comment by jajanzen** [comment]
Also works in Python 3.13.9
